Docker add ASCII banner

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -37,6 +37,9 @@ FROM ${BASE_IMAGE} AS base
 ## ⚠️ ARG may specified again because the FROM directive resets ARGs
 ## (but their default value is retained if set previously)
 
+ARG SCIKITPLOT_VERSION=0.4.0.post1
+ENV SCIKITPLOT_VERSION=${SCIKITPLOT_VERSION}
+
 # LABEL org.opencontainers.image.base.name="${BASE_IMAGE}"
 LABEL maintainer="The scikit-plots developers <scikit-plots.github.io/dev>"
 # LABEL org.opencontainers.image.authors="The scikit-plots developers <scikit-plots.github.io/dev>"
@@ -154,8 +157,7 @@ RUN apt-get update \
   ; \
   ## Cleanup to reduce image size
   apt-get clean \
-  && rm -rf /var/lib/apt/lists/* \
-  ;
+  && rm -rf /var/lib/apt/lists/*
 
 ######################################################################
 ## OS dependencies
@@ -272,13 +274,9 @@ RUN apt-get update --yes \
   ## Install separately and ignore failure
   ## MKL (Intel Math Kernel Library)
   apt-get install --yes --no-install-recommends libmkl-dev || true; \
-  ## Fix permissions as root
-  fix-permissions "$HOME" \
-  && fix-permissions "$CONDA_DIR"; \
   ## Cleanup to reduce image size
   apt-get clean \
-  && rm -rf /var/lib/apt/lists/* \
-  ;
+  && rm -rf /var/lib/apt/lists/*
 
 ## Add a second conditional RUN block for large or optional packages:
 RUN if [ "$EXTENDED_PACKAGES" = "true" ]; then \
@@ -301,10 +299,7 @@ RUN if [ "$EXTENDED_PACKAGES" = "true" ]; then \
       graphviz \
       ## Vector graphics editor
       inkscape \
-    || true; \
-    ## Fix permissions as root
-    fix-permissions "$HOME" \
-    && fix-permissions "$CONDA_DIR"; \
+    || { echo "Failed to install extended packages"; }; \
     ## Cleanup to reduce image size
     apt-get clean \
     && rm -rf /var/lib/apt/lists/* \
@@ -329,16 +324,6 @@ RUN if [ "$EXTENDED_PACKAGES" = "true" ]; then \
 #   || echo "Script not found, skipping..." \
 #   '
 
-## ASCII banner for scikit-plots
-# COPY ./docker/scripts/bashrc /etc/bash.bashrc
-# RUN chmod a+rwx /etc/bash.bashrc || true
-RUN if [ -f ./docker/scripts/bashrc ]; then \
-      cp ./docker/scripts/bashrc /etc/bash.bashrc; \
-      chmod a+rwx /etc/bash.bashrc; \
-    else \
-      echo "Bashrc file not found, skipping copy."; \
-    fi
-
 ######################################################################
 ## default user
 ## cut -d: -f1 /etc/passwd
@@ -347,66 +332,51 @@ RUN if [ -f ./docker/scripts/bashrc ]; then \
 ## Switch back to the notebook default user "jovyan" to avoid accidental container runs as root
 USER ${NB_UID}
 
-## Fix permissions as jovyan
-## Setup work directory for backward-compatibility
-RUN fix-permissions "$HOME" \
-  && mkdir -p /home/$NB_USER/work || true
-
 ######################################################################
 ## default environment (e.g. conda, mamba, pipenv)
 ######################################################################
 
-## Create conda environment from environment.yml and clean cache
-COPY "./docker/env_conda/base.yml" "/tmp/base.yml"
-COPY "./docker/env_conda/default.yml" "/tmp/default.yml"
-COPY "./docker/env_conda/extended.yml" "/tmp/extended.yml"
-COPY "./docker/env_conda/environment.yml" "/tmp/environment.yml"
+## Copy your project files to leverage Docker cache
+COPY docker /work/docker
+COPY docker/env_conda/environment.yml /work/
+COPY requirements /work/requirements/
 
+# micromamba and post create steps
+RUN bash -i -c ". docker/scripts/all_post_create.sh && rm -rf /work/docker"
+
+# mamba as conda
+COPY ./docker/env_conda/ /tmp/
 ## Optionally, Ensure mamba installations (if needed)
 ## RUN conda install -n base conda-forge::mamba -y
-# RUN conda install -n base -c conda-forge mamba -y
-
-# RUN mamba create -n "py311" python=3.11 ipykernel -y
-RUN mamba env create -n "py311" -f "/tmp/base.yml" \
-  || { echo "Failed to create environment py311"; exit 1; }; \
-  conda info --envs; \
+## RUN conda install -n base -c conda-forge mamba -y
+## RUN mamba create -n "py312" python=3.11 ipykernel -y
+RUN mamba env create -n "py312" -f "/tmp/base.yml" \
+  || { echo "Failed to create environment py312"; }; \
   ## Clean mamba and fix permissions, Fails but continues
   mamba clean --all -f -y || true; \
-  rm -rf ${HOME}/.cache || true; \
-  ## Fix permissions as jovyan
-  fix-permissions "$HOME" \
-  && fix-permissions "${CONDA_DIR}" \
-  ;
-
-# Update environment with default.yml (always applied), Fails and exits script cleanly
-RUN mamba env update -n "py311" -f "/tmp/default.yml" \
-  || { echo "Failed to apply default environment"; exit 0; }; \
+  rm -rf ${HOME}/.cache || true
+## Update environment with default.yml (always applied), Fails and exits script cleanly
+RUN mamba env update -n "py312" -f "/tmp/default.yml" \
+  || { echo "Failed to apply default environment"; }; \
   ## Clean mamba and fix permissions, Fails but continues
   mamba clean --all -f -y || true; \
-  rm -rf ${HOME}/.cache || true; \
-  ## Fix permissions as jovyan
-  fix-permissions "$HOME" \
-  && fix-permissions "${CONDA_DIR}" \
-  ;
-
-# Conditionally apply extended.yml (only if EXTENDED_PACKAGES=true), Fails and exits script cleanly
+  rm -rf ${HOME}/.cache || true
+## Conditionally apply extended.yml (only if EXTENDED_PACKAGES=true), Fails and exits script cleanly
 RUN if [ "$EXTENDED_PACKAGES" = "true" ]; then \
     echo "Installing extended packages..."; \
-    mamba env update -n "py311" -f "/tmp/extended.yml" \
-    || { echo "Failed to apply extended environment"; exit 0; }; \
+    mamba env update -n "py312" -f "/tmp/extended.yml" \
+    || { echo "Failed to apply extended environment"; }; \
     ## Clean mamba and fix permissions, Fails but continues
     mamba clean --all -f -y || true; \
-    rm -rf ${HOME}/.cache || true; \
-    ## Fix permissions as jovyan
-    fix-permissions "$HOME" \
-    && fix-permissions "${CONDA_DIR}" \
+    rm -rf ${HOME}/.cache || true \
     ; \
   else \
     echo "Skipping extended packages."; \
   fi
 
-## Set shell to use conda run — safer than `conda activate`
-# SHELL ["conda", "run", "-n", "py311", "/bin/bash", "-c"]
+## Fix permissions as jovyan
+RUN fix-permissions "$HOME" \
+  && fix-permissions "${CONDA_DIR}" || true
 
 ######################################################################
 ## JUPYTER
@@ -426,9 +396,11 @@ EXPOSE 9000-9001
 ## Configure container startup
 ENTRYPOINT ["tini", "-g", "--"]
 ## Set the command to start Jupyter lab with the specified port
-# CMD ["bash", "-c", "source /etc/bash.bashrc && jupyter notebook --notebook-dir=/tf --ip 0.0.0.0 --no-browser --allow-root"]
+## CMD ["bash", "-c", "source /etc/bash.bashrc && jupyter notebook --notebook-dir=/tf --ip 0.0.0.0 --no-browser --allow-root"]
+## CMD bash -c 'source ~/.bash-bashrc 2>/dev/null || true; exec start-notebook.py --port "${JUPYTER_PORT:-8888}"'
+## CMD bash -c '[ -f ~/.bash-bashrc ] && source ~/.bash-bashrc; exec start-notebook.py --port "${JUPYTER_PORT:-8888}"'
 # CMD ["start-notebook.sh"]
-CMD source /etc/bash.bashrc && start-notebook.py --port ${JUPYTER_PORT}
+CMD bash -c 'start-notebook.py --port "${JUPYTER_PORT:-8888}"'
 
 ######################################################################
 ## WORKDIR
diff --git a/docker/docker-compose.yml b/docker/docker-compose.yml
--- a/docker/docker-compose.yml
+++ b/docker/docker-compose.yml
@@ -73,21 +73,24 @@ networks:
 ## Declares services (containers) that will be run by Docker Compose
 services:
 
-  ## docker compose -f 'docker/docker-compose.yml' up -d --build 'scikit-plots_latest-python-3.11-slim'
-  "scikit-plots_latest-python-3.11-slim":  # Name of the service (can be any name you choose)
-    container_name: "scikit-plots_latest-python-3.11-slim"
+  ## docker compose -f 'docker/docker-compose.yml' up -d --build 'scikit-plots_latest-python-3.12-slim'
+  "scikit-plots_latest-python-3.12-slim":  # Name of the service (can be any name you choose)
+    container_name: "scikit-plots_latest-python-3.12-slim"
     stdin_open: true  # Keeps STDIN open (for interactive mode)
-    tty: true  # Allocates a pseudo-TTY
+    tty: true  # Allocates a pseudo-TTY,  Keeps container running with interactive terminal
     ## Restart policy: always restart the container if it stops
     # restart: "always"
-    image: python:3.11-slim  # 130+Mb (No internal CUDA, relies on host CUDA)
+    image: python:3.12-slim  # 130+Mb (No internal CUDA, relies on host CUDA)
+    ## (Optionally) Use Dockerfile
+    # build: ...
+    ## Change User
     # user: root  # Ensure the container runs as "root", jupyter default "jovyan"
     ## Adjust the working directory as needed
     ## by image source default for jupyter images "/home/jovyan/work"
     ## by image source default for codespaces images "/workspaces"
     working_dir: /work
     volumes:
-      - ..:/work
+      - ..:/work  # Optional: bind mount your code for live edits
     # env_file:
     #   - .env  # Load environment from file
     environment:
@@ -114,22 +117,21 @@ services:
     # sudo -n true &&
     # { ... } runs in current shell — can exit or affect current environment.
     # ( ... ) runs in a subshell — changes inside don't affect the parent script.
+    # git curl procps build-essential gfortran ninja-build
     entrypoint: >-
       bash -c "
-        command -v curl >/dev/null 2>&1 || {
-          echo '📦 Installing dev tools (if sudo available)...';
-          { apt-get update -y &&
-            apt-get install -y sudo gosu git curl procps build-essential gfortran ninja-build; } ||
-          echo '⚠️ Failed or skipped installing dev tools';
+        command -v sudo >/dev/null 2>&1 || {
+          echo '📦 Installing sudo...';
+          { apt-get update -y;
+            apt-get install -y sudo gosu git;
+          } || echo '⚠️ Failed or skipped installing sudo';
         };
 
-        command -v micromamba >/dev/null 2>&1 || {
-          echo '📦 Installing Conda/Mamba environment...';
-          bash docker/scripts/all_post_create.sh ||
-          echo '⚠️ Failed or skipped installing dev tools';
-        };
-
-        exec bash"
+        ## Add bash-first-run-notice.txt
+        [ -f docker/scripts/bash_first_run_notice.sh ] && \
+        { . docker/scripts/bash_first_run_notice.sh; } || true
+        exec bash
+        fi"
 
     # 👇 if using Compose V2 CLI this enables GPU access (Compose V2+	YAML equivalent of --gpus all)
     # gpus: all  # ← this is the preferred modern way to request all GPUs
@@ -145,12 +147,60 @@ services:
     #       devices:
     #         - capabilities: [gpu]
 
+  ## docker compose -f 'docker/docker-compose.yml' up -d --build 'scikit-plots_latest-python-3.11-slim'
+  "scikit-plots_latest-python-3.11-slim":  # Name of the service (can be any name you choose)
+    container_name: "scikit-plots_latest-python-3.11-slim"
+    stdin_open: true  # Keeps STDIN open (for interactive mode)
+    tty: true  # Allocates a pseudo-TTY,  Keeps container running with interactive terminal
+    ## Restart policy: always restart the container if it stops
+    # restart: "always"
+    # image: python:3.11-slim  # 130+Mb (No internal CUDA, relies on host CUDA)
+    ## (Optionally) Use Dockerfile
+    # build: ...
+    build:
+      context: ../
+      dockerfile: ./docker/Dockerfile.python  # fast mini image
+      args:
+        PY_VERSION: "${PY_VERSION:-3.11}"
+        # SCIKITPLOT_VERSION: "${SCIKITPLOT_VERSION:-}"  # for dev or SCIKITPLOT_VERSION=
+        SCIKITPLOT_VERSION: "${SCIKITPLOT_VERSION:-0.4.0.post1}"  # for release
+    ## Change User
+    # user: root  # Ensure the container runs as "root", jupyter default "jovyan"
+    ## Adjust the working directory as needed
+    ## by image source default for jupyter images "/home/jovyan/work"
+    ## by image source default for codespaces images "/workspaces"
+    working_dir: /work
+    volumes:
+      - ..:/work  # Optional: bind mount your code for live edits
+    # env_file:
+    #   - .env  # Load environment from file
+    environment:
+      # This overrides the ENV at runtime. So the container will have:
+      # Equivalent to IS_DOCKERENV = os.path.exists("/.dockerenv")
+      - IS_DOCKERENV=true  # 🐳 Used to detect if the app is running inside Docker
+    ports:
+      - "8890:8890"  # Exposing port placeholder for Jupyter Notebook (default 8888)
+    networks:
+      - "back_tier"  # Connect to the defined network for backend services
+      - "front_tier"  # Connect to the defined network for frontend services
+      # - "llm-rag-workshop_back_tier"  # Connect to the external network for LLM RAG workshop
+
+    ## Works only with Docker 20.10.0+ and the host-gateway feature enabled.
+    ## macOS & Windows (host.docker.internal is built-in DNS name that maps to the host machine.)
+    ## Only needed for Linux, You must manually map it using extra_hosts, like this:
+    extra_hosts:
+      - "host.docker.internal:host-gateway"  # Makes host accessible as "host.docker.internal"
+
+    ## if both provided default only work entrypoint so command used to as entrypoint argument
+    # entrypoint: bash  # bash -c "<everything inside the quotes>"
+    # command:
+
 
   ## docker compose -f 'docker/docker-compose.yml' up -d --build 'scikit-plots_latest-jupyter'
   "scikit-plots_latest-jupyter":  # Name of the service (can be any name you choose)
     container_name: "scikit-plots_latest-jupyter"
     # stdin_open: true  # Keeps STDIN open (for interactive mode)
-    # tty: true  # Allocates a pseudo-TTY
+    # tty: true  # Allocates a pseudo-TTY,  Keeps container running with interactive terminal
     ## Restart policy: always restart the container if it stops
     restart: "always"
     ## If the host has CUDA installed, the container can use it without installing CUDA inside.
@@ -158,12 +208,17 @@ services:
     ## ubuntu:latest  # Use a lightweight base image (No internal CUDA, relies on host CUDA)
     ## python:3.12-slim  # Use the Python slim image (lightweight) (No internal CUDA, relies on host CUDA)
     # image: "jupyter/tensorflow-notebook:latest"  # Image compressed 1.8+Gb (No internal CUDA, relies on host CUDA)
+    ## (Optionally) Use Dockerfile
+    # build: ...
     build:
       context: ../
       dockerfile: ./docker/Dockerfile  # 15+Gb compressed image
       args:
         BASE_IMAGE: "${BASE_IMAGE:-jupyter/tensorflow-notebook:latest}"
         NB_PASS: "jovyan"
+        # SCIKITPLOT_VERSION: "${SCIKITPLOT_VERSION:-}"  # for dev or SCIKITPLOT_VERSION=
+        SCIKITPLOT_VERSION: "${SCIKITPLOT_VERSION:-0.4.0.post1}"  # for release
+    ## Change User
     # user: root  # Ensure the container runs as "root", jupyter default "jovyan"
     ## Adjust the working directory as needed
     ## by image source default for jupyter images "/home/jovyan/work"
@@ -192,7 +247,7 @@ services:
   "scikit-plots_latest-gpu-jupyter":  # Name of the service (can be any name you choose)
     container_name: "scikit-plots_latest-gpu-jupyter"
     # stdin_open: true  # Keeps STDIN open (for interactive mode)
-    # tty: true  # Allocates a pseudo-TTY
+    # tty: true  # Allocates a pseudo-TTY,  Keeps container running with interactive terminal
     ## Restart policy: always restart the container if it stops
     restart: "always"
     ## If the host has CUDA installed, the container can use it without installing CUDA inside.
@@ -200,12 +255,15 @@ services:
     ## ubuntu:latest  # Use a lightweight base image (No internal CUDA, relies on host CUDA)
     ## python:3.12-slim  # Use the Python slim image (lightweight) (No internal CUDA, relies on host CUDA)
     # image: "jupyter/tensorflow-notebook:latest"  # Image compressed 1.8+Gb (No internal CUDA, relies on host CUDA)
+    ## (Optionally) Use Dockerfile
+    # build: ...
     build:
       context: ../
       dockerfile: ./docker/Dockerfile
       args:
         BASE_IMAGE: "${BASE_IMAGE:-jupyter/tensorflow-notebook:latest}"
         NB_PASS: "jovyan"
+    ## Change User
     # user: root  # Ensure the container runs as "root", jupyter default "jovyan"
     ## Adjust the working directory as needed
     ## by image source default for jupyter images "/home/jovyan/work"
