Release version 0.4.0.post0

diff --git a/tools/ci/cirrus_wheels.yml b/tools/ci/cirrus_wheels.yml
--- a/tools/ci/cirrus_wheels.yml
+++ b/tools/ci/cirrus_wheels.yml
@@ -39,12 +39,14 @@ linux_aarch64_task:
         CIBW_BUILD_FRONTEND: "pip; args: --no-build-isolation"
 
   initial_setup_script: |
-    apt update
-    apt install -y python3-venv python-is-python3 gfortran libatlas-base-dev libgfortran5 eatmydata
+    # Added set -e in scripts to ensure the build stops on any failure.
+    set -e
+    apt update && apt install -y python3-venv python-is-python3 gfortran libatlas-base-dev libgfortran5 eatmydata
     git fetch origin
     bash ./tools/wheels/cibw_before_build.sh ${PWD}
     which python
     echo $CIRRUS_CHANGE_MESSAGE
+
   <<: *BUILD_AND_STORE_WHEELS
 
 
@@ -77,6 +79,7 @@ macosx_arm64_task:
     CIBW_ARCHS: arm64
 
   build_script: |
+    set -e
     brew install micromamba gfortran
     micromamba shell init -s bash -p ~/micromamba
     source ~/.bash_profile
@@ -122,11 +125,12 @@ wheels_upload_task:
     platform: linux
     cpu: 1
 
-  env:
-    NUMPY_STAGING_UPLOAD_TOKEN: ENCRYPTED[!5a69522ae0c2af9edb2bc1cdfeaca6292fb3666d9ecd82dca0615921834a6ce3b702352835d8bde4ea2a9ed5ef8424ac!]
-    NUMPY_NIGHTLY_UPLOAD_TOKEN: ENCRYPTED[4376691390321cd5e76613ec21de8456cc0af0164971dd9542f985a017dc30ccb4d40e60f59184618e2d55afd63e93b7]
+  # env:
+  #   SKPLT_STAGING_UPLOAD_TOKEN: ENCRYPTED[!5a69522ae0c2af9edb2bc1cdfeaca6292fb3666d9ecd82dca0615921834a6ce3b702352835d8bde4ea2a9ed5ef8424ac!]
+  #   SKPLT_NIGHTLY_UPLOAD_TOKEN: ENCRYPTED[4376691390321cd5e76613ec21de8456cc0af0164971dd9542f985a017dc30ccb4d40e60f59184618e2d55afd63e93b7]
 
   upload_script: |
+    set -e
     apt-get update
     apt-get install -y curl wget
     export IS_SCHEDULE_DISPATCH="false"
