test circleci

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -30,6 +30,16 @@ permissions:
   packages: read  # required to fetch internal or private CodeQL packs
   security-events: write  # for github/codeql-action/autobuild to send a status report
 
+# simultaneity
+concurrency:
+  ## The group key defines how GitHub Actions groups workflow runs together.
+  ## github.workflow → The name of the workflow file.
+  ## github.ref      → The branch or tag the workflow is running on.
+  group: ${{ github.workflow }}-${{ github.ref }}
+  ## If you push multiple times quickly, older runs would continue even though newer ones have started.
+  ## Canceling previous runs reduces resource usage and speeds up feedback.
+  cancel-in-progress: true
+
 jobs:
   analyze:
     name: CodeQL Analyze (${{ matrix.language }})
@@ -76,65 +86,66 @@ jobs:
         # your codebase is analyzed, see https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages
 
     steps:
-    - name: Checkout Repository
-      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
-      with:
-        persist-credentials: false
-        fetch-depth: 0
+      - name: Checkout (cloned) repository with full history
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          persist-credentials: false  # Prevents accidental credential exposure
+          submodules: true  # Fetch Hugo themes (true OR recursive)
+          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
 
-    # Initializes the CodeQL tools for scanning.
-    - name: CodeQL Initialize
-      uses: github/codeql-action/init@5618c9fc1e675841ca52c1c6b1304f5255a905a0  # codeql-bundle-v2.19.0
-      with:
-        languages: ${{ matrix.language }}
-        # build-mode: ${{ matrix.build-mode }}
-        # source-root: src
-        # If you wish to specify custom queries, you can do so here or in a config file.
-        # By default, queries listed here will override any specified in a config file.
-        # Prefix the list here with "+" to use these queries and those in the config file.
-        # queries: ./path/to/local/query, your-org/your-repo/queries@main
-        # For more details on CodeQL's query packs, refer to:
-        # https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
-        # queries: security-extended,security-and-quality
+      # Initializes the CodeQL tools for scanning.
+      - name: CodeQL Initialize
+        uses: github/codeql-action/init@5618c9fc1e675841ca52c1c6b1304f5255a905a0  # codeql-bundle-v2.19.0
+        with:
+          languages: ${{ matrix.language }}
+          # build-mode: ${{ matrix.build-mode }}
+          # source-root: src
+          # If you wish to specify custom queries, you can do so here or in a config file.
+          # By default, queries listed here will override any specified in a config file.
+          # Prefix the list here with "+" to use these queries and those in the config file.
+          # queries: ./path/to/local/query, your-org/your-repo/queries@main
+          # For more details on CodeQL's query packs, refer to:
+          # https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
+          # queries: security-extended,security-and-quality
 
-    # Autobuild attempts to build any compiled languages (C/C++, C#, Go, Java, or Swift).
-    # If this step fails, then you should remove it and run the build manually (see below)
-    - name: CodeQL Autobuild
-      if: matrix.language != 'c-cpp'
-      uses: github/codeql-action/autobuild@5618c9fc1e675841ca52c1c6b1304f5255a905a0  # codeql-bundle-v2.19.0
+      # Autobuild attempts to build any compiled languages (C/C++, C#, Go, Java, or Swift).
+      # If this step fails, then you should remove it and run the build manually (see below)
+      - name: CodeQL Autobuild
+        if: matrix.language != 'c-cpp'
+        uses: github/codeql-action/autobuild@5618c9fc1e675841ca52c1c6b1304f5255a905a0  # codeql-bundle-v2.19.0
 
-    # ℹ️ Command-line programs to run using the OS shell.
-    # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
-    # 📚 https://git.io/JvXDl
-    # ✏️ If the Autobuild fails above, remove it and uncomment the following three lines
-    #    and modify them (or add more) to build your code if your project
-    #    uses a compiled language, please refer to the EXAMPLE below for guidance.
-    # - run: |
-    #     echo "Run, Build Application using script"
-    #     ./location_of_script_within_repo/buildscript.sh
-    # - if: matrix.build-mode == 'manual'
-    #   shell: bash
-    #   run: |
-    #     echo 'If you are using a "manual" build mode for one or more of the' \
-    #       'languages you are analyzing, replace this with the commands to build' \
-    #       'your code, for example:'
-    #     echo '  make bootstrap'
-    #     echo '  make release'
-    #     exit 1
+      # ℹ️ Command-line programs to run using the OS shell.
+      # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
+      # 📚 https://git.io/JvXDl
+      # ✏️ If the Autobuild fails above, remove it and uncomment the following three lines
+      #    and modify them (or add more) to build your code if your project
+      #    uses a compiled language, please refer to the EXAMPLE below for guidance.
+      # - run: |
+      #     echo "Run, Build Application using script"
+      #     ./location_of_script_within_repo/buildscript.sh
+      # - if: matrix.build-mode == 'manual'
+      #   shell: bash
+      #   run: |
+      #     echo 'If you are using a "manual" build mode for one or more of the' \
+      #       'languages you are analyzing, replace this with the commands to build' \
+      #       'your code, for example:'
+      #     echo '  make bootstrap'
+      #     echo '  make release'
+      #     exit 1
 
-    - name: Manual Set up Python
-      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v5.4.0
-      if: matrix.language == 'c-cpp'
-      with:
-        python-version: '3.11'
+      - name: Manual Set up Python
+        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v5.4.0
+        if: matrix.language == 'c-cpp'
+        with:
+          python-version: '3.11'
 
-    - name: Manual Build Library
-      if: matrix.language == 'c-cpp'
-      run: |
-        pip install -r requirements/all.txt
-        pip install --no-build-isolation --no-cache-dir -e .[dev,build,test,docs] -v
+      - name: Manual Build Library
+        if: matrix.language == 'c-cpp'
+        run: |
+          pip install -r requirements/all.txt
+          pip install --no-build-isolation --no-cache-dir -e .[dev,build,test,docs] -v
 
-    - name: CodeQL Perform Analysis
-      uses: github/codeql-action/analyze@5618c9fc1e675841ca52c1c6b1304f5255a905a0  # codeql-bundle-v2.19.0
-      with:
-        category: "/language:${{matrix.language}}"
+      - name: CodeQL Perform Analysis
+        uses: github/codeql-action/analyze@5618c9fc1e675841ca52c1c6b1304f5255a905a0  # codeql-bundle-v2.19.0
+        with:
+          category: "/language:${{matrix.language}}"
