docs

diff --git a/.github/workflows/deploy-docs.yml b/.github/workflows/deploy-docs.yml
--- a/.github/workflows/deploy-docs.yml
+++ b/.github/workflows/deploy-docs.yml
@@ -42,15 +42,15 @@ jobs:
           fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
           ref: ${{ github.event.inputs.branch || 'main' }}
 
-      - name: Validate Version Input
-        env:
-          VERSION: ${{ github.event.inputs.version }}
-        run: |
-          echo "$VERSION"
-          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+$ && "$VERSION" != "dev" && "$VERSION" != "stable" && "$VERSION" != "prev" ]]; then
-            echo "❌ Invalid version format: $VERSION"
-            exit 1
-          fi
+      # - name: Validate Version Input
+      #   env:
+      #     VERSION: ${{ github.event.inputs.version }}
+      #   run: |
+      #     echo "$VERSION"
+      #     if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+$ && "$VERSION" != "dev" && "$VERSION" != "stable" && "$VERSION" != "prev" ]]; then
+      #       echo "❌ Invalid version format: $VERSION"
+      #       exit 1
+      #     fi
 
       - name: Set up Python
         uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
